// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type PgCast struct {
	Castsource int32
	Casttarget int32
}

type PgClass struct {
	Oid          int32
	Relname      string
	Relnamespace int32
}

type PgConstraint struct {
	Conname  string
	Contype  string
	Conrelid int32
}

type PgDatabase struct {
	Oid           int32
	Datname       string
	Datallowconn  bool
	Datistemplate bool
}

type PgEventTrigger struct {
	Evtname string
}

type PgExtension struct {
	Extname string
}

type PgForeignDataWrapper struct {
	Fdwname string
}

type PgIndex struct {
	Indexname  string
	Schemaname string
	Tablename  string
}

type PgLanguage struct {
	Lanname string
	Lanispl bool
}

type PgMatview struct {
	Matviewname string
	Schemaname  string
}

type PgNamespace struct {
	Oid     int32
	Nspname string
}

type PgPolicy struct {
	Policyname string
	Schemaname string
	Tablename  string
}

type PgProc struct {
	Oid          int32
	Proname      string
	Pronamespace int32
	Prokind      string
}

type PgPublication struct {
	Pubname string
}

type PgRole struct {
	Rolname string
}

type PgRule struct {
	Rulename   string
	Schemaname string
	Tablename  string
}

type PgSequence struct {
	Sequencename string
	Schemaname   string
}

type PgSubscription struct {
	Subname string
	Subdbid int32
}

type PgTable struct {
	Tablename  string
	Schemaname string
}

type PgTablespace struct {
	Spcname string
}

type PgTrigger struct {
	Tgname       string
	Tgrelid      int32
	Tgisinternal bool
}

type PgType struct {
	Typname      string
	Typtype      string
	Typnamespace int32
}

type PgView struct {
	Viewname   string
	Schemaname string
}
