// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPrimaryKeyColumns = `-- name: GetPrimaryKeyColumns :many
SELECT c.conname, a.attname
FROM pg_constraint c
JOIN pg_class t ON c.conrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
JOIN unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord) ON true
JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
WHERE n.nspname = $1 AND t.relname = $2 AND c.contype = 'p'
ORDER BY k.ord
`

type GetPrimaryKeyColumnsParams struct {
	Nspname string
	Relname string
}

type GetPrimaryKeyColumnsRow struct {
	Conname string
	Attname string
}

func (q *Queries) GetPrimaryKeyColumns(ctx context.Context, arg GetPrimaryKeyColumnsParams) ([]GetPrimaryKeyColumnsRow, error) {
	rows, err := q.db.Query(ctx, getPrimaryKeyColumns, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrimaryKeyColumnsRow
	for rows.Next() {
		var i GetPrimaryKeyColumnsRow
		if err := rows.Scan(&i.Conname, &i.Attname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableColumns = `-- name: GetTableColumns :many

SELECT column_name FROM information_schema.columns
WHERE table_schema = $1 AND table_name = $2
ORDER BY ordinal_position
`

type GetTableColumnsParams struct {
	TableSchema interface{}
	TableName   interface{}
}

// Table-level category queries ($1 = schema name, $2 = table name)
func (q *Queries) GetTableColumns(ctx context.Context, arg GetTableColumnsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getTableColumns, arg.TableSchema, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_name interface{}
		if err := rows.Scan(&column_name); err != nil {
			return nil, err
		}
		items = append(items, column_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableColumnsDetailed = `-- name: GetTableColumnsDetailed :many
SELECT
    c.column_name,
    c.data_type,
    c.is_nullable,
    c.column_default,
    c.character_maximum_length,
    COALESCE(coll.collname, '') AS collation
FROM information_schema.columns c
LEFT JOIN pg_attribute a ON a.attrelid = ($1 || '.' || $2)::regclass AND a.attname = c.column_name
LEFT JOIN pg_collation coll ON coll.oid = a.attcollation
WHERE c.table_schema = $1 AND c.table_name = $2
ORDER BY c.ordinal_position
`

type GetTableColumnsDetailedParams struct {
	Column1 pgtype.Text
	Column2 pgtype.Text
}

type GetTableColumnsDetailedRow struct {
	ColumnName             interface{}
	DataType               interface{}
	IsNullable             interface{}
	ColumnDefault          interface{}
	CharacterMaximumLength interface{}
	Collation              string
}

func (q *Queries) GetTableColumnsDetailed(ctx context.Context, arg GetTableColumnsDetailedParams) ([]GetTableColumnsDetailedRow, error) {
	rows, err := q.db.Query(ctx, getTableColumnsDetailed, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableColumnsDetailedRow
	for rows.Next() {
		var i GetTableColumnsDetailedRow
		if err := rows.Scan(
			&i.ColumnName,
			&i.DataType,
			&i.IsNullable,
			&i.ColumnDefault,
			&i.CharacterMaximumLength,
			&i.Collation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableInfo = `-- name: GetTableInfo :one
SELECT tableowner, tablespace
FROM pg_tables
WHERE schemaname = $1 AND tablename = $2
LIMIT 1
`

type GetTableInfoParams struct {
	Schemaname string
	Tablename  string
}

type GetTableInfoRow struct {
	Tableowner string
	Tablespace pgtype.Text
}

func (q *Queries) GetTableInfo(ctx context.Context, arg GetTableInfoParams) (GetTableInfoRow, error) {
	row := q.db.QueryRow(ctx, getTableInfo, arg.Schemaname, arg.Tablename)
	var i GetTableInfoRow
	err := row.Scan(&i.Tableowner, &i.Tablespace)
	return i, err
}

const listCasts = `-- name: ListCasts :many

SELECT '(' || castsource::regtype || ' AS ' || casttarget::regtype || ')' FROM pg_cast ORDER BY 1
`

// Database-level category queries (run against a specific database)
func (q *Queries) ListCasts(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listCasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogs = `-- name: ListCatalogs :many
SELECT nspname FROM pg_namespace
WHERE nspname = 'information_schema' OR nspname LIKE 'pg\_%'
ORDER BY 1
`

func (q *Queries) ListCatalogs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCatalogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nspname string
		if err := rows.Scan(&nspname); err != nil {
			return nil, err
		}
		items = append(items, nspname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConstraints = `-- name: ListConstraints :many
SELECT c.conname || ' (' || CASE c.contype
    WHEN 'p' THEN 'primary key'
    WHEN 'f' THEN 'foreign key'
    WHEN 'u' THEN 'unique'
    WHEN 'c' THEN 'check'
    ELSE c.contype::text
END || ')'
FROM pg_constraint c
JOIN pg_class t ON c.conrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
WHERE n.nspname = $1 AND t.relname = $2
ORDER BY 1
`

type ListConstraintsParams struct {
	Nspname string
	Relname string
}

func (q *Queries) ListConstraints(ctx context.Context, arg ListConstraintsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listConstraints, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabases = `-- name: ListDatabases :many

SELECT datname FROM pg_database
WHERE datallowconn AND NOT datistemplate
ORDER BY datname
`

// Server-level queries (run against maintenance DB)
func (q *Queries) ListDatabases(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var datname string
		if err := rows.Scan(&datname); err != nil {
			return nil, err
		}
		items = append(items, datname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT t.typname FROM pg_type t
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = $1 AND t.typtype = 'd'
ORDER BY 1
`

func (q *Queries) ListDomains(ctx context.Context, nspname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDomains, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var typname string
		if err := rows.Scan(&typname); err != nil {
			return nil, err
		}
		items = append(items, typname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTriggers = `-- name: ListEventTriggers :many
SELECT evtname FROM pg_event_trigger ORDER BY 1
`

func (q *Queries) ListEventTriggers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listEventTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var evtname string
		if err := rows.Scan(&evtname); err != nil {
			return nil, err
		}
		items = append(items, evtname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensions = `-- name: ListExtensions :many
SELECT extname FROM pg_extension ORDER BY 1
`

func (q *Queries) ListExtensions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var extname string
		if err := rows.Scan(&extname); err != nil {
			return nil, err
		}
		items = append(items, extname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignDataWrappers = `-- name: ListForeignDataWrappers :many
SELECT fdwname FROM pg_foreign_data_wrapper ORDER BY 1
`

func (q *Queries) ListForeignDataWrappers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listForeignDataWrappers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fdwname string
		if err := rows.Scan(&fdwname); err != nil {
			return nil, err
		}
		items = append(items, fdwname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFunctions = `-- name: ListFunctions :many
SELECT p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')'
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
WHERE n.nspname = $1 AND p.prokind = 'f'
ORDER BY 1
`

func (q *Queries) ListFunctions(ctx context.Context, nspname string) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listFunctions, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many
SELECT lanname FROM pg_language WHERE lanispl ORDER BY 1
`

func (q *Queries) ListLanguages(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var lanname string
		if err := rows.Scan(&lanname); err != nil {
			return nil, err
		}
		items = append(items, lanname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterializedViews = `-- name: ListMaterializedViews :many
SELECT matviewname FROM pg_matviews WHERE schemaname = $1 ORDER BY 1
`

func (q *Queries) ListMaterializedViews(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMaterializedViews, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var matviewname string
		if err := rows.Scan(&matviewname); err != nil {
			return nil, err
		}
		items = append(items, matviewname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT policyname FROM pg_policies
WHERE schemaname = $1 AND tablename = $2
ORDER BY 1
`

type ListPoliciesParams struct {
	Schemaname string
	Tablename  string
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPolicies, arg.Schemaname, arg.Tablename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var policyname string
		if err := rows.Scan(&policyname); err != nil {
			return nil, err
		}
		items = append(items, policyname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcedures = `-- name: ListProcedures :many
SELECT p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')'
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
WHERE n.nspname = $1 AND p.prokind = 'p'
ORDER BY 1
`

func (q *Queries) ListProcedures(ctx context.Context, nspname string) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listProcedures, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublications = `-- name: ListPublications :many
SELECT pubname FROM pg_publication ORDER BY 1
`

func (q *Queries) ListPublications(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPublications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var pubname string
		if err := rows.Scan(&pubname); err != nil {
			return nil, err
		}
		items = append(items, pubname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT rolname FROM pg_roles
ORDER BY rolname
`

func (q *Queries) ListRoles(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rolname string
		if err := rows.Scan(&rolname); err != nil {
			return nil, err
		}
		items = append(items, rolname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemas = `-- name: ListSchemas :many
SELECT nspname FROM pg_namespace
WHERE nspname NOT LIKE 'pg\_%' AND nspname <> 'information_schema'
ORDER BY 1
`

func (q *Queries) ListSchemas(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nspname string
		if err := rows.Scan(&nspname); err != nil {
			return nil, err
		}
		items = append(items, nspname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSequences = `-- name: ListSequences :many
SELECT sequencename FROM pg_sequences WHERE schemaname = $1 ORDER BY 1
`

func (q *Queries) ListSequences(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSequences, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sequencename string
		if err := rows.Scan(&sequencename); err != nil {
			return nil, err
		}
		items = append(items, sequencename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT subname FROM pg_subscription
WHERE subdbid = (SELECT oid FROM pg_database WHERE datname = current_database())
ORDER BY 1
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subname string
		if err := rows.Scan(&subname); err != nil {
			return nil, err
		}
		items = append(items, subname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableColumns = `-- name: ListTableColumns :many
SELECT column_name || ' ' || data_type FROM information_schema.columns
WHERE table_schema = $1 AND table_name = $2
ORDER BY ordinal_position
`

type ListTableColumnsParams struct {
	TableSchema interface{}
	TableName   interface{}
}

func (q *Queries) ListTableColumns(ctx context.Context, arg ListTableColumnsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listTableColumns, arg.TableSchema, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var column_1 interface{}
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableIndexes = `-- name: ListTableIndexes :many
SELECT indexname FROM pg_indexes
WHERE schemaname = $1 AND tablename = $2
ORDER BY 1
`

type ListTableIndexesParams struct {
	Schemaname string
	Tablename  string
}

func (q *Queries) ListTableIndexes(ctx context.Context, arg ListTableIndexesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTableIndexes, arg.Schemaname, arg.Tablename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var indexname string
		if err := rows.Scan(&indexname); err != nil {
			return nil, err
		}
		items = append(items, indexname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableRules = `-- name: ListTableRules :many
SELECT rulename FROM pg_rules
WHERE schemaname = $1 AND tablename = $2
ORDER BY 1
`

type ListTableRulesParams struct {
	Schemaname string
	Tablename  string
}

func (q *Queries) ListTableRules(ctx context.Context, arg ListTableRulesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTableRules, arg.Schemaname, arg.Tablename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rulename string
		if err := rows.Scan(&rulename); err != nil {
			return nil, err
		}
		items = append(items, rulename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableTriggers = `-- name: ListTableTriggers :many
SELECT tg.tgname FROM pg_trigger tg
JOIN pg_class t ON tg.tgrelid = t.oid
JOIN pg_namespace n ON t.relnamespace = n.oid
WHERE n.nspname = $1 AND t.relname = $2 AND NOT tg.tgisinternal
ORDER BY 1
`

type ListTableTriggersParams struct {
	Nspname string
	Relname string
}

func (q *Queries) ListTableTriggers(ctx context.Context, arg ListTableTriggersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTableTriggers, arg.Nspname, arg.Relname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tgname string
		if err := rows.Scan(&tgname); err != nil {
			return nil, err
		}
		items = append(items, tgname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTables = `-- name: ListTables :many

SELECT tablename FROM pg_tables WHERE schemaname = $1 ORDER BY 1
`

// Schema-level category queries ($1 = schema name)
func (q *Queries) ListTables(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTables, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tablename string
		if err := rows.Scan(&tablename); err != nil {
			return nil, err
		}
		items = append(items, tablename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablespaces = `-- name: ListTablespaces :many
SELECT spcname FROM pg_tablespace
ORDER BY spcname
`

func (q *Queries) ListTablespaces(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTablespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var spcname string
		if err := rows.Scan(&spcname); err != nil {
			return nil, err
		}
		items = append(items, spcname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT t.typname FROM pg_type t
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = $1 AND t.typtype IN ('c', 'e', 'r')
ORDER BY 1
`

func (q *Queries) ListTypes(ctx context.Context, nspname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTypes, nspname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var typname string
		if err := rows.Scan(&typname); err != nil {
			return nil, err
		}
		items = append(items, typname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViews = `-- name: ListViews :many
SELECT viewname FROM pg_views WHERE schemaname = $1 ORDER BY 1
`

func (q *Queries) ListViews(ctx context.Context, schemaname string) ([]string, error) {
	rows, err := q.db.Query(ctx, listViews, schemaname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var viewname string
		if err := rows.Scan(&viewname); err != nil {
			return nil, err
		}
		items = append(items, viewname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
