// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createServer = `-- name: CreateServer :one
INSERT INTO server (
    user_id, servergroup_id, name, host, port, maintenance_db, username, ssl_mode
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, servergroup_id, name, host, port, maintenance_db, username, password, role, ssl_mode, comment, discovery_id, hostaddr, db_res, passfile, sslcert, keyfile, rootcert, crlfile, service, bgcolor, fgcolor, connect_timeout, use_ssh_tunnel, ssh_host, ssh_port, ssh_username, ssh_password, ssh_keyfile, shared
`

type CreateServerParams struct {
	UserID        int64  `json:"user_id"`
	ServergroupID int64  `json:"servergroup_id"`
	Name          string `json:"name"`
	Host          string `json:"host"`
	Port          int64  `json:"port"`
	MaintenanceDb string `json:"maintenance_db"`
	Username      string `json:"username"`
	SslMode       string `json:"ssl_mode"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRowContext(ctx, createServer,
		arg.UserID,
		arg.ServergroupID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.MaintenanceDb,
		arg.Username,
		arg.SslMode,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServergroupID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.MaintenanceDb,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.SslMode,
		&i.Comment,
		&i.DiscoveryID,
		&i.Hostaddr,
		&i.DbRes,
		&i.Passfile,
		&i.Sslcert,
		&i.Keyfile,
		&i.Rootcert,
		&i.Crlfile,
		&i.Service,
		&i.Bgcolor,
		&i.Fgcolor,
		&i.ConnectTimeout,
		&i.UseSshTunnel,
		&i.SshHost,
		&i.SshPort,
		&i.SshUsername,
		&i.SshPassword,
		&i.SshKeyfile,
		&i.Shared,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, user_id, servergroup_id, name, host, port, maintenance_db, username, password, role, ssl_mode, comment, discovery_id, hostaddr, db_res, passfile, sslcert, keyfile, rootcert, crlfile, service, bgcolor, fgcolor, connect_timeout, use_ssh_tunnel, ssh_host, ssh_port, ssh_username, ssh_password, ssh_keyfile, shared FROM server
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetServerByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetServerByID(ctx context.Context, arg GetServerByIDParams) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServerByID, arg.ID, arg.UserID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServergroupID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.MaintenanceDb,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.SslMode,
		&i.Comment,
		&i.DiscoveryID,
		&i.Hostaddr,
		&i.DbRes,
		&i.Passfile,
		&i.Sslcert,
		&i.Keyfile,
		&i.Rootcert,
		&i.Crlfile,
		&i.Service,
		&i.Bgcolor,
		&i.Fgcolor,
		&i.ConnectTimeout,
		&i.UseSshTunnel,
		&i.SshHost,
		&i.SshPort,
		&i.SshUsername,
		&i.SshPassword,
		&i.SshKeyfile,
		&i.Shared,
	)
	return i, err
}

const listServersByGroup = `-- name: ListServersByGroup :many
SELECT 
    s.id, 
    s.name, 
    s.host, 
    s.port, 
    s.maintenance_db, 
    s.username, 
    sg.name AS group_name
FROM server s
INNER JOIN servergroup sg ON s.servergroup_id = sg.id
WHERE s.user_id = ?
ORDER BY sg.name, s.name
`

type ListServersByGroupRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Host          string `json:"host"`
	Port          int64  `json:"port"`
	MaintenanceDb string `json:"maintenance_db"`
	Username      string `json:"username"`
	GroupName     string `json:"group_name"`
}

func (q *Queries) ListServersByGroup(ctx context.Context, userID int64) ([]ListServersByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listServersByGroup, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServersByGroupRow
	for rows.Next() {
		var i ListServersByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.MaintenanceDb,
			&i.Username,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
