// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createServer = `-- name: CreateServer :one
INSERT INTO server (
    user_id, servergroup_id, name, host, port, maintenance_db, username, ssl_mode
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, servergroup_id, name, host, port, maintenance_db, username, password, role, ssl_mode, comment, discovery_id, hostaddr, db_res, passfile, sslcert, keyfile, rootcert, crlfile, service, bgcolor, fgcolor, connect_timeout, use_ssh_tunnel, ssh_host, ssh_port, ssh_username, ssh_password, ssh_keyfile, shared
`

type CreateServerParams struct {
	UserID        int64  `json:"user_id"`
	ServergroupID int64  `json:"servergroup_id"`
	Name          string `json:"name"`
	Host          string `json:"host"`
	Port          int64  `json:"port"`
	MaintenanceDb string `json:"maintenance_db"`
	Username      string `json:"username"`
	SslMode       string `json:"ssl_mode"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRowContext(ctx, createServer,
		arg.UserID,
		arg.ServergroupID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.MaintenanceDb,
		arg.Username,
		arg.SslMode,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServergroupID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.MaintenanceDb,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.SslMode,
		&i.Comment,
		&i.DiscoveryID,
		&i.Hostaddr,
		&i.DbRes,
		&i.Passfile,
		&i.Sslcert,
		&i.Keyfile,
		&i.Rootcert,
		&i.Crlfile,
		&i.Service,
		&i.Bgcolor,
		&i.Fgcolor,
		&i.ConnectTimeout,
		&i.UseSshTunnel,
		&i.SshHost,
		&i.SshPort,
		&i.SshUsername,
		&i.SshPassword,
		&i.SshKeyfile,
		&i.Shared,
	)
	return i, err
}

const getQueryHistoryByID = `-- name: GetQueryHistoryByID :one
SELECT id, user_id, tab_id, connection_id, query_text, executed_at, duration_ms, status, rows_affected
FROM query_history
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetQueryHistoryByIDParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) GetQueryHistoryByID(ctx context.Context, arg GetQueryHistoryByIDParams) (QueryHistory, error) {
	row := q.db.QueryRowContext(ctx, getQueryHistoryByID, arg.ID, arg.UserID)
	var i QueryHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TabID,
		&i.ConnectionID,
		&i.QueryText,
		&i.ExecutedAt,
		&i.DurationMs,
		&i.Status,
		&i.RowsAffected,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, user_id, servergroup_id, name, host, port, maintenance_db, username, password, role, ssl_mode, comment, discovery_id, hostaddr, db_res, passfile, sslcert, keyfile, rootcert, crlfile, service, bgcolor, fgcolor, connect_timeout, use_ssh_tunnel, ssh_host, ssh_port, ssh_username, ssh_password, ssh_keyfile, shared FROM server
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetServerByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetServerByID(ctx context.Context, arg GetServerByIDParams) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServerByID, arg.ID, arg.UserID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServergroupID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.MaintenanceDb,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.SslMode,
		&i.Comment,
		&i.DiscoveryID,
		&i.Hostaddr,
		&i.DbRes,
		&i.Passfile,
		&i.Sslcert,
		&i.Keyfile,
		&i.Rootcert,
		&i.Crlfile,
		&i.Service,
		&i.Bgcolor,
		&i.Fgcolor,
		&i.ConnectTimeout,
		&i.UseSshTunnel,
		&i.SshHost,
		&i.SshPort,
		&i.SshUsername,
		&i.SshPassword,
		&i.SshKeyfile,
		&i.Shared,
	)
	return i, err
}

const getUserWorkspace = `-- name: GetUserWorkspace :one
SELECT user_id, active_tab_id, layout_metadata, updated_at FROM user_workspaces
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetUserWorkspace(ctx context.Context, userID int64) (UserWorkspace, error) {
	row := q.db.QueryRowContext(ctx, getUserWorkspace, userID)
	var i UserWorkspace
	err := row.Scan(
		&i.UserID,
		&i.ActiveTabID,
		&i.LayoutMetadata,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceTab = `-- name: InsertWorkspaceTab :exec
INSERT INTO workspace_tabs (id, user_id, title, connection_id, query_text, tab_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type InsertWorkspaceTabParams struct {
	ID           string         `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	Title        string         `json:"title"`
	ConnectionID sql.NullString `json:"connection_id"`
	QueryText    sql.NullString `json:"query_text"`
	TabOrder     int64          `json:"tab_order"`
}

func (q *Queries) InsertWorkspaceTab(ctx context.Context, arg InsertWorkspaceTabParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspaceTab,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.ConnectionID,
		arg.QueryText,
		arg.TabOrder,
	)
	return err
}

const listQueryHistory = `-- name: ListQueryHistory :many
SELECT id, user_id, tab_id, connection_id, query_text, executed_at, duration_ms, status, rows_affected
FROM query_history
WHERE user_id = ?
  AND (? = '' OR connection_id = ?)
ORDER BY executed_at DESC, id DESC
LIMIT 50
`

type ListQueryHistoryParams struct {
	UserID       sql.NullInt64  `json:"user_id"`
	Column2      interface{}    `json:"column_2"`
	ConnectionID sql.NullString `json:"connection_id"`
}

func (q *Queries) ListQueryHistory(ctx context.Context, arg ListQueryHistoryParams) ([]QueryHistory, error) {
	rows, err := q.db.QueryContext(ctx, listQueryHistory, arg.UserID, arg.Column2, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryHistory
	for rows.Next() {
		var i QueryHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TabID,
			&i.ConnectionID,
			&i.QueryText,
			&i.ExecutedAt,
			&i.DurationMs,
			&i.Status,
			&i.RowsAffected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersByGroup = `-- name: ListServersByGroup :many
SELECT 
    s.id, 
    s.name, 
    s.host, 
    s.port, 
    s.maintenance_db, 
    s.username, 
    sg.name AS group_name
FROM server s
INNER JOIN servergroup sg ON s.servergroup_id = sg.id
WHERE s.user_id = ?
ORDER BY sg.name, s.name
`

type ListServersByGroupRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Host          string `json:"host"`
	Port          int64  `json:"port"`
	MaintenanceDb string `json:"maintenance_db"`
	Username      string `json:"username"`
	GroupName     string `json:"group_name"`
}

func (q *Queries) ListServersByGroup(ctx context.Context, userID int64) ([]ListServersByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listServersByGroup, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServersByGroupRow
	for rows.Next() {
		var i ListServersByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.MaintenanceDb,
			&i.Username,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTabs = `-- name: ListWorkspaceTabs :many
SELECT id, user_id, title, connection_id, query_text, tab_order, created_at FROM workspace_tabs
WHERE user_id = ?
ORDER BY tab_order, created_at
`

func (q *Queries) ListWorkspaceTabs(ctx context.Context, userID sql.NullInt64) ([]WorkspaceTab, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceTabs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceTab
	for rows.Next() {
		var i WorkspaceTab
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.ConnectionID,
			&i.QueryText,
			&i.TabOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordQueryHistory = `-- name: RecordQueryHistory :exec
INSERT INTO query_history (user_id, tab_id, connection_id, query_text, executed_at, duration_ms, status, rows_affected)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, ?, ?, ?)
`

type RecordQueryHistoryParams struct {
	UserID       sql.NullInt64  `json:"user_id"`
	TabID        sql.NullString `json:"tab_id"`
	ConnectionID sql.NullString `json:"connection_id"`
	QueryText    string         `json:"query_text"`
	DurationMs   sql.NullInt64  `json:"duration_ms"`
	Status       sql.NullString `json:"status"`
	RowsAffected sql.NullInt64  `json:"rows_affected"`
}

func (q *Queries) RecordQueryHistory(ctx context.Context, arg RecordQueryHistoryParams) error {
	_, err := q.db.ExecContext(ctx, recordQueryHistory,
		arg.UserID,
		arg.TabID,
		arg.ConnectionID,
		arg.QueryText,
		arg.DurationMs,
		arg.Status,
		arg.RowsAffected,
	)
	return err
}

const replaceWorkspaceTabs = `-- name: ReplaceWorkspaceTabs :exec
DELETE FROM workspace_tabs
WHERE user_id = ?
`

func (q *Queries) ReplaceWorkspaceTabs(ctx context.Context, userID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, replaceWorkspaceTabs, userID)
	return err
}

const saveUserWorkspace = `-- name: SaveUserWorkspace :exec
INSERT INTO user_workspaces (user_id, active_tab_id, layout_metadata, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    active_tab_id = excluded.active_tab_id,
    layout_metadata = excluded.layout_metadata,
    updated_at = CURRENT_TIMESTAMP
`

type SaveUserWorkspaceParams struct {
	UserID         int64          `json:"user_id"`
	ActiveTabID    string         `json:"active_tab_id"`
	LayoutMetadata sql.NullString `json:"layout_metadata"`
}

func (q *Queries) SaveUserWorkspace(ctx context.Context, arg SaveUserWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, saveUserWorkspace, arg.UserID, arg.ActiveTabID, arg.LayoutMetadata)
	return err
}
